services:
 db:
   expose:
     - "3306"
   environment:
     APP_ENV: "local"
     TZ: "Asia/Tokyo"
     MYSQL_ROOT_PASSWORD: "root"
   env_file: ./docker/env/.env.local
 api:
   ports:
     - 8080:8080
   environment:
     APP_ENV: "local"
     TZ: "Asia/Tokyo"
     MYSQL_ROOT_PASSWORD: "root"
   env_file: ./docker/env/.env.local