version: "3.7"

services:
  test:
    image: "pytest"
    container_name: "pytest"
    depends_on:
      - testdb
    build:
      context: ./docker/test
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8100:8100"
    volumes:
      - ./app:/usr/src/app/app:cached
      - ./scripts:/usr/src/app/scripts:cached
      - ./tests:/usr/src/app/tests:cached
      - ./db:/usr/src/app/db:cached
    working_dir: /usr/src/app/scripts
    command: bash -c "./test.sh"
    networks:
      - fastapi_test_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development
  testdb:
    image: "fastapi_testdb"
    container_name: "fastapi_testdb"
    build:
      context: ./docker/test-db
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - 5432:5432
    networks:
      - fastapi_test_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development
networks:
  default:
    external:
      name: bridge
  fastapi_test_network:
    name: fastapi_test_network
    driver: bridge
    external: true

