version: "3.7"

services:
  test:
    image: "pytest"
    container_name: "pytest"
    depends_on:
      - test-db
    build:
      context: ./docker/test
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ./app:/usr/src/app/app:cached
      - ./scripts:/usr/src/app/scripts:cached
      - ./tests:/usr/src/app/tests:cached
    working_dir: /usr/src/app/scripts
    command: bash -c "./test.sh"
    networks:
      - fastapi_test_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.test
  test-db:
    image: "fastapi_starter_test-db:0.1.0"
    container_name: "fastapi_starter_test-db"
    build:
      context: ./docker/test-db
      dockerfile: Dockerfile
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./docker/test-db/conf.d:/etc/mysql/conf.d:cached
      - ./log/db:/var/log/mysql:cached
    networks:
      - fastapi_test_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.test
networks:
  default:
    external:
      name: bridge
  fastapi_test_network:
    name: fastapi_test_network
    driver: bridge
    external: true

